version: '3.3'

services:
  webapp:
    build: .
    container_name: medic-webapp
    ports:
      - "5988:5988"
    networks:
      - medic-net
    volumes:
      - .:/srv/
      - ./api/logs/:/srv/api/logs/
      - ./sentinel/logs:/srv/sentinel/logs/
    depends_on:
      - couchdb
      # - nginx
    env_file:
      - ./environments/.medic

  # nginx:
  #   container_name: nginx
  #   image: nginx:alpine
  #   ports:
  #     - "81:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx/logs/:/var/log/nginx
  #     - ./nginx/ssl-keys:/etc/nginx/ssl
  #     - ./nginx/sites-available:/etc/nginx/sites-enabled
  #   depends_on:
  #     - couchdb
  #   networks:
  #     - medic-net

  couchdb:
    container_name: couchdb-image
    image: 'couchdb:2.2'
    networks:
      - medic-net
    ports:
      - "5984:5984"
      - "4370:4369"
      - "9101:9100"
    env_file:
      - ./environments/.couch
    volumes:
      - couchdb-data:/opt/couchdb/data
      - ./couchdb/local.ini:/opt/couchdb/etc/local.ini
      - ./couchdb/logs:/var/logs/couchdb

volumes:
  couchdb-data:

networks:
  medic-net:
    labels:
      com.medic-net.description: "docker containers compose internal network"
