version: '3.3'

services:
  webapp:
    build: .
    container_name: medic-webapp
    ports:
      - "5989:5988"
    networks:
      - medic-net
    depends_on:
      - couchdb
      - nginx
    volumes:
      - .:/srv/
      - ./api/logs/:/srv/api/logs/
      - ./sentinel/logs:/srv/sentinel/logs/
    environment:
      - COUCH_URL=http://admin:pass@couchdb-image:5984/medic
      - COUCH_NODE_NAME=couchdb@couchdb-image

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs/:/var/log/nginx
      - ./nginx/ssl-keys:/etc/nginx/ssl
      - ./nginx/sites-available:/etc/nginx/sites-enabled
    depends_on:
      - couchdb
    networks:
      - medic-net

  couchdb:
    hostname: localhost
    container_name: couchdb-image
    image: 'couchdb:2.2'
    networks:
      - medic-net
    ports:
      - "5985:5984"
      # - "4370:4369"
      # - "9101:9100"ping
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=pass
      - NODENAME=couchdb-image
    volumes:
      - couchdb-data:/opt/couchdb/data
      - ./couchdb/local.ini:/opt/couchdb/etc/local.ini
      - ./couchdb/logs:/var/logs/couchdb

volumes:
  couchdb-data:

networks:
  # medic-couchdb-net:
  #   driver: host
  #   labels:
  #     com.medic-net.description: "couchdb"
  #     com.medic-net.organization: "Livinggoods"

  medic-net:
    labels:
      com.medic-net.description: "docker containers compose internal network"
      com.medic-net.organization: "Livinggoods"
